### ISSUE TITLE
Run migrations parallel

### ISSUE THREAD

**Issue by XPCegeka** [XPCegeka/ElasticUp#9]
Instead of batches of data where each batch is processed sequentially, we want to run migrations parallel.

Time figures are needed when
- running sequentially
- parallel

**Comment by tomboon** [comment]
There is now a BatchUpdateOperation that allows for parallel batch updates ( DegreeOfParallellism parameter in descriptor).

The 3 previously existing BatchUpdateTypeOperations are marked obsolete.
